### PR TITLE
Add files via Upload

### PR DESCRIPTION
**Pull request by blueork**
Add Past Papers of COAL and Data Structures via Upload.

### CODE REVIEW

**Comment by saleha-muzammil** [comment]
Hello! Kindly confirm if the course content is same or not , or we can make a separate branch for Islamabad

**Comment by saleha-muzammil** [comment]
Yeah lets create a separate branch for isb, you can compile all the materials and lmk , ill create a new branch then you can pull a req there

**Comment by blueork** [comment]
Understood. Also, how should I organize the content? Should I make a separate sub-folder for Islamabad Campus within the respective course folder or a separate folder altogether?

**Comment by saleha-muzammil** [comment]
i think we should create a separate branch

**Pull request closed without merging**
